apiVersion: v1
kind: Service
metadata:
  name: memory-hungry-api
  namespace: memory-sim
  labels:
    app.kubernetes.io/name: memory-hungry-api
spec:
  selector:
    app.kubernetes.io/name: memory-hungry-api
  ports:
    - name: http
      port: 80
      targetPort: http
